#pragma once
#include <SDL2/SDL.h>
#include <unordered_map>
#include <string>
#include <vector>

class Game
{
public:
  
  // Constracter
  Game();
  
  // Initializer
  bool Initialize();
  
  // Game Looper
  void RunLoop();
  
  // ShutDown Game
  void Shutdown();
  
  // Add or Remove Actor
  void AddActor(class Actor* actor);
  void RemoveActor(class Actor* actor);
  
  // Add Sprite
  void AddSprite(class SpriteComponent* sprite);
  void RemoveSprite(class SpriteComponent* sprite);
  
  SDL_Texture* GetTexture(const std::string& filename);
  
  // chapter specific
  void AddField(class Field* field);
  void RemoveField(class Field* field);
  //class Filed* GetFields() {return mFields;}
private:
  // Helper functions for RunLoop()
  void ProcessInput();
  void UpdateGame();
  void GenerateOutput();
  void LoadData();
  void UnloadData();
  
  // map of textures
  std::unordered_map<std::string, SDL_Texture*> mTextures;
  
  // All the sprite components drawn
  std::vector<class SpriteComponent*> mSprites;
  
  // the pointer of Window generated by SDL
  SDL_Window *mWindow;
  SDL_Renderer *mRenderer; // graphic organizer
  
  // continue instractor
  bool mlsRunning;
  // elapsed time from SDL_init
  Uint32 mTicksCount;
  
  // GameObject
  std::vector<class Actor*> mActors;
  std::vector<class Actor*> mPendingActors;
  
  bool mUpdatingActors;
  
  // Game specific
  class Ship* mShip;
  class Field* mFields;
};
